name: render

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

jobs:
  render-quarto-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Render Quarto site
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html
        path: site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site/_site
        publish_branch: site-html 

